/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-1",
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_o9QTdJGpm",
        "userPoolWebClientId": "cga7pglb3p5v06p5u8ndvugoo",
        oauth: {
            domain: 'https://63owxhpddl.execute-api.us-east-1.amazonaws.com/production',
            scope: ['email', 'openid'],
            redirectSignIn: 'http://localhost:3000/',
            redirectSignOut: 'http://localhost:3000/',
            responseType: 'code',
          },
    },
    // "API": {
    //     "endpoints": [
    //         {
    //             "name": "ItemsAPI",
    //             "endpoint": "https://63owxhpddl.execute-api.us-east-1.amazonaws.com/production"
    //         }
    //     ]
    // }
};


export default awsconfig;
